package @package@;

import com.google.gwt.i18n.client.Constants;

/** 
 * App config constants generated by the build process.
 */
public interface AppConfig extends Constants {

	public String version();


}